#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
اسکریپت بررسی وضعیت Security Group و راهنمایی برای باز کردن پورت 5000
"""

print("=" * 70)
print("🔍 بررسی وضعیت پورت 5000 روی سرور EC2")
print("=" * 70)
print()
print("❌ پورت 5000 از بیرون قابل دسترسی نیست!")
print()
print("📋 دلیل احتمالی:")
print("   - Security Group در AWS اجازه دسترسی به پورت 5000 را نمی‌دهد")
print("   - یا iptables/firewalld روی سرور پورت را مسدود کرده است")
print()
print("=" * 70)
print("✅ راه حل: باز کردن پورت 5000 در AWS Security Group")
print("=" * 70)
print()
print("مراحل زیر را دنبال کنید:")
print()
print("1️⃣  وارد AWS Console شوید:")
print("    https://console.aws.amazon.com/ec2/")
print()
print("2️⃣  به بخش Security Groups بروید:")
print("    در منوی سمت چپ، روی 'Security Groups' کلیک کنید")
print()
print("3️⃣  Security Group مرتبط با اینستنس خود را پیدا کنید:")
print("    - اینستنس شما: i-xxxxxxxxx (در EC2 Instances قابل مشاهده است)")
print("    - یا جستجو بر اساس نام/تگ")
print()
print("4️⃣  روی Security Group کلیک کرده و به تب 'Inbound rules' بروید")
print()
print("5️⃣  روی دکمه 'Edit inbound rules' کلیک کنید")
print()
print("6️⃣  یک قانون جدید اضافه کنید:")
print("    ┌─────────────┬──────────┬──────────────┬──────────────┐")
print("    │ Type        │ Protocol │ Port Range   │ Source       │")
print("    ├─────────────┼──────────┼──────────────┼──────────────┤")
print("    │ Custom TCP  │ TCP      │ 5000         │ 0.0.0.0/0    │")
print("    │             │          │              │ (یا IP شما)  │")
print("    └─────────────┴──────────┴──────────────┴──────────────┘")
print()
print("    توضیحات:")
print("    - Type: Custom TCP")
print("    - Protocol: TCP")
print("    - Port Range: 5000")
print("    - Source: ")
print("      • برای دسترسی عمومی: 0.0.0.0/0")
print("      • فقط IP شما: My IP (یا IP دستی)")
print()
print("7️⃣  روی 'Save rules' کلیک کنید")
print()
print("=" * 70)
print("🧪 تست پس از اعمال تغییرات:")
print("=" * 70)
print()
print("بعد از ذخیره قوانین، چند ثانیه صبر کنید و سپس:")
print()
print("1. مرورگر: http://52.23.157.88:5000")
print("2. یا دستور:")
print("   curl http://52.23.157.88:5000/api/status")
print()
print("=" * 70)
print("🔧 روش جایگزین: استفاده از AWS CLI")
print("=" * 70)
print()
print("اگر AWS CLI نصب دارید، می‌توانید از دستور زیر استفاده کنید:")
print()
print("aws ec2 authorize-security-group-ingress \\")
print("    --group-id sg-xxxxxxxxx \\")
print("    --protocol tcp \\")
print("    --port 5000 \\")
print("    --cidr 0.0.0.0/0")
print()
print("نکته: group-id را از EC2 Console کپی کنید")
print()
print("=" * 70)
print("⚠️ نکات امنیتی:")
print("=" * 70)
print()
print("- اگر فقط خودتان نیاز به دسترسی دارید، به جای 0.0.0.0/0 از IP خود استفاده کنید")
print("- می‌توانید بعداً قوانین را ویرایش کرده و Source را محدودتر کنید")
print("- برای محیط تولید، استفاده از Load Balancer + HTTPS توصیه می‌شود")
print()
print("=" * 70)
